version: "3.9"
services:
api:
build: .
environment:
BROKER_URL: amqp://guest:guest@rabbitmq//
JWT_SECRET: "dev-secret" # replace with RS256 in prod
ports: ["8080:8080"]
depends_on: [rabbitmq]


worker:
build: .
command: ["celery", "-A", "app.celery_app.celery_app", "worker", "-l", "INFO"]
environment:
BROKER_URL: amqp://guest:guest@rabbitmq//


rabbitmq:
image: rabbitmq:3-management
ports: ["5672:5672", "15672:15672"]
